### PR TITLE
Feat/angular 17

### PR DESCRIPTION
**Pull request by fh1ch**
**What kind of change does this PR introduce?** (check one with "x")

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

The project uses Angular 15 for the main demo app.

**What is the new behavior?**

The project uses Angular 17 for the main demo app.

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Also bumps the minimal required Angular version to `17.0` and rxjs version to `7.8.0` using a breaking change in feca9fa167ec941b733a8a88ef4d57a771b33bec.

### CODE REVIEW

**Comment by timowolf** [comment]
@fh1ch Many thanks for updating. Let me know when ready for review.

**Comment by fh1ch** [comment]
@timowolf @kfenner this PR is more or less ready and updates the project setup to Angular 17. The only remaining question is, if we should bump the minimal peer-dep version within https://github.com/siemens/ngx-datatable/blob/master/projects/ngx-datatable/package.json#L6-L12 and probably also mark this as a breaking change. WDYT?

**Comment by timowolf** [comment]
@fh1ch Yes, let us do so.

**Comment by fh1ch** [comment]
> @fh1ch Many thanks for updating. Let me know when ready for review.

We're ready to role here. Back to you 🏓

**Comment by kfenner** [comment]
> @timowolf @kfenner this PR is more or less ready and updates the project setup to Angular 17. The only remaining question is, if we should bump the minimal peer-dep version within https://github.com/siemens/ngx-datatable/blob/master/projects/ngx-datatable/package.json#L6-L12 and probably also mark this as a breaking change. WDYT?

@fh1ch @timowolf Is there any need for this, or even any benefit right now? If we need to fix a bug or something, only apps on Angular 17 will be able to use it...

**Comment by timowolf** [comment]
> > @timowolf @kfenner this PR is more or less ready and updates the project setup to Angular 17. The only remaining question is, if we should bump the minimal peer-dep version within https://github.com/siemens/ngx-datatable/blob/master/projects/ngx-datatable/package.json#L6-L12 and probably also mark this as a breaking change. WDYT?
> 
> @fh1ch @timowolf Is there any need for this, or even any benefit right now? If we need to fix a bug or something, only apps on Angular 17 will be able to use it...

I think it is fine. They can use it anyway but get a warning. This opens up for using ng17 features.

**Review by timowolf — APPROVED** [review]
Works like a charm. Many thanks.

**Pull request merged**
