### PR TITLE
feat(rows): wrapper for pre applying directives

### PR DESCRIPTION
**Pull request by chintankavathia**
Introduced `DatatableRowDefComponent` which can be used by consumers to pre apply certain directives on each row.

Usage:

```html
<ngx-datatable>
  <ng-template rowDef>
    <datatable-row-def cdkDrag />
  </ng-template>
</ngx-datatable>
```

**What kind of change does this PR introduce?** (check one with "x")

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by chintankavathia** [comment]
@spike-rabbit This is a proposal for allowing consumers to pre apply directives (e.g cdk drag drop)  at row levels. Please have a look and provide your feedback.

**Comment by timowolf** [comment]
Many thanks. May you provide an example for it. Maybe add the CDK to the demo and support drag and drop.

**Review by timowolf — CHANGES_REQUESTED** [review]
Please provide an example.

**Comment by chintankavathia** [comment]
> Please provide an example.

@timowolf I have added an example to show the CDK drag drop usage.

**Review by timowolf — CHANGES_REQUESTED** [review]
Many thanks. I really like it and it works perfect. Just some minor little things and I think a bit of documentation would be useful here.

**Review by timowolf — APPROVED** [review]
Many thanks for the update.

**Pull request merged**
