### PR TITLE
fix(a11y): add aria-label for datatable tree icons

### PR DESCRIPTION
**Pull request by chintankavathia**
**What kind of change does this PR introduce?** (check one with "x")

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Currently there is no a11y label for expand collapse icons
**What is the new behavior?**
This change will add aria-label to expand collapse icons
**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by chintankavathia** [comment]
@kfenner Please review this MR.
Thanks !

**Review by kfenner — APPROVED** [review]
Good quick fix, I like it 👍

**Review by timowolf — APPROVED** [review]
LGTM.

**Review by fh1ch — APPROVED** [review]
@chintankavathia thanks a ton for the MR. No inputs from my end 🙇 

LGTM 👍

**Pull request merged**
